[tool.ruff.lint]
select = ["ALL"]  # all checklists available

ignore = [
    "D203",  # ignore white lines before class
    "D213",  # ignore resume in second line
    "N812", #ignore Expectec Conditions as EC (because of selenium community)
]


[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
